### ISSUE TITLE
Config rutas 

### ISSUE THREAD

**Issue by GeraZorzoni** [snahuel99/nahuel-mercado_liebre#1]
https://github.com/snahuel99/nahuel-mercado_liebre/blob/9e83558b2f5773f9eac86200c23577db75d04d69/src/views/home.html#L41-L43

Nahu buenas! Creo que tenes algunde detalle de las rutas que no te permite ingresar a cada pagina haciendo click en ingresar y el crea tu cuenta, no estan funcionando en render, creo que en el href no coincide con la configuracion de las rutas en App. abrazo!

**Comment by snahuel99** [comment]
Hola Gerardo, solucionado. Saludos

**Comment by GeraZorzoni** [comment]
Genial! abrazo
